on:
  workflow_call:

jobs:
  wc_run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: 'pip'

      - run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r PHASE_1/requirements.txt

      - uses: actions/cache@v2
        id: cache-geo-names
        with:
          path: ./geonames/
          key: geonames-${{ hashFiles('**/*.zip') }}
          restore-key: |
            ${{ runner.os }}-geonames-

      - name: Download (or load from cache) country to geoid map file
        run: |
          mkdir -p ./geonames/
          wget https://cgi.cse.unsw.edu.au/~z5312157/country-to-geo.zip -O ./geonames/country-to-geo.zip
          unzip ./geonames/country-to-geo.zip -d ./geonames/
          mv ./geonames/CountryToGeoID-sorted.txt PHASE_1/API_SourceCode/country-to-geo.txt
        if: steps.cache-geo-names.outputs.cache-hit != 'true'

      - name: Lint with black
        run: black --check PHASE_1/API_SourceCode/

      - name: Make sure no __pycache__ and no .pyc file is present
        run: if git ls-files | grep __pycache__ || git-ls-files | grep '.pyc$' ; then exit 1; fi

      - name: Make sure posts.json wasn't commited
        run: if git ls-files | grep posts.json ; then exit 1; fi
          
      - name: Run all tests
        run: ./PHASE_1/run-all-tests.sh
