on:
  workflow_call:

jobs:
  wc_run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: 'pip'

      - run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r PHASE_1/requirements.txt

      - name: Lint with black
        run: black --check PHASE_1/API_SourceCode/

      - name: Make sure no __pycache__ and no .pyc file is present
        run: if git ls-files | grep __pycache__ || git-ls-files | grep '.pyc$' ; then exit 1; fi

      - name: Make sure posts.json wasn't commited
        run: if git ls-files | grep posts.json ; then exit 1; fi
          
      - name: Run all tests
        run: ./PHASE_1/run-all-tests.sh
